# -*- coding: utf-8 -*-
"""MELI prueba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xNKbLNdubQBr06Gr6tWhKxjce_gPFEIv

#**Challenge MELI**

## **0. Limpieza y consistencia de la base de datos**
"""

# ==========================================
# 0. CARGAR BASE DE DATOS
# ==========================================

import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

file_path = '/content/df_challenge_meli - df_challenge_meli.csv'
df = pd.read_csv(file_path)

df.head()

df.info()

# ==========================================
# 1. CONSISTENCIA BASE DE DATOS
# ==========================================

# Renombrar columnas
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
df.head()

#Validar si tiene duplicados por url
df.duplicated(subset=["url"]).sum()

#Validar que no haya productos repetidos por un mismo proveedor, con distintos precios

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
grouped_counts = df.groupby(['seller_nickname', 'titulo']).agg(
    count=('price', 'size'),
    min_price=('price', 'min'),
    max_price=('price', 'max'),
    std_price=('price', 'std')
).reset_index()

grouped_counts = grouped_counts.sort_values(by='count', ascending=False)
grouped_counts = grouped_counts[grouped_counts['count'] > 2]
grouped_counts

#Eliminar filas que tienen productos repetidos por vendedor, título y precio
print(f"Shape of DataFrame before dropping duplicates: {df.shape}")

df = df.drop_duplicates(subset=['seller_nickname', 'titulo', 'price'])

print(f"Shape of DataFrame after dropping duplicates: {df.shape}")
display(df.head())

#Validar que no haya productos repetidos por un mismo proveedor, con distintos precios

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
grouped_counts = df.groupby(['seller_nickname', 'titulo']).agg(
    count=('price', 'size'),
    min_price=('price', 'min'),
    max_price=('price', 'max'),
    std_price=('price', 'std')
).reset_index()

grouped_counts = grouped_counts.sort_values(by='count', ascending=False)
grouped_counts = grouped_counts[grouped_counts['count'] > 2]
grouped_counts

#Validar variables que tienen nulos
#Para Seller_reputation se crea una categoria de desconocido
#Para el precio se imputa los valores con la mediana por categoria
df.isnull().sum().sort_values(ascending=False)

#Identificar productos que tienen precio 0 o negativo
df[df["price"] <= 0]

#Consistencia: no se identifican productos donde el precio regular sea menor al precio con descuento
df[df["regular_price"] < df["price"]]

#Consistencia: no se identifican productos que tienen regular price 0 o negativo
df[df["regular_price"] <= 0]

#Tipo de datos: se define el tipo de datos numerico

df["price"] = pd.to_numeric(df["price"], errors="coerce")
df["regular_price"] = pd.to_numeric(df["regular_price"], errors="coerce")
df["stock"] = pd.to_numeric(df["stock"], errors="coerce")

# Corregir el valor de 'price' en la fila 183732 y 183733, con la información encontrada directamente en la página
df.loc[183732, "price"] = 5130.0
df.loc[183733, "price"] = 5130.0

#Convertir variables en tipo fecha y booleano
df["tim_day"] = pd.to_datetime(df["tim_day"])
df["is_refurbished"] = df["is_refurbished"].astype(bool)

df["logistic_type"].value_counts()

df["condition"].value_counts()

#Se valida que no hayan productos con stock negativo

df[df["stock"] < 0]

#Validar por cada categoria el promedio, mediana y desviación de los precios para imputar datos

pd.set_option('display.float_format', '{:.2f}'.format)
category_price_stats = df.groupby('category_name')['price'].agg(['mean', 'median', 'std', 'min', 'max'])
category_price_stats

#Identificar outliers

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mticker

# Calculate mean price for each category and sort them
category_order = df.groupby('category_name')['price'].mean().sort_values(ascending=False).index

# Define the number of categories per plot
categories_per_plot = 10

# Iterate and create boxplots for batches of categories
for i in range(0, len(category_order), categories_per_plot):
    current_categories = category_order[i : i + categories_per_plot]
    df_subset = df[df['category_name'].isin(current_categories)]

    plt.figure(figsize=(18, 8))
    ax = sns.boxplot(x='category_name', y='price', data=df_subset, order=current_categories)
    plt.xticks(rotation=90)
    plt.title(f'Distribución de Precios por Categoría (Batch {i//categories_per_plot + 1})')
    plt.xlabel('Nombre de la Categoría')
    plt.ylabel('Precio (en miles)')
    plt.grid(axis='y', linestyle='--', alpha=0.7)

    # Format y-axis to show values in thousands
    formatter = mticker.FuncFormatter(lambda x, p: f'{x/1000:.0f}K')
    ax.yaxis.set_major_formatter(formatter)

    plt.tight_layout()
    plt.show()

# Calcular los percentiles 1% y 99% para la columna 'price'
lower_bound = df['price'].quantile(0.01)
upper_bound = df['price'].quantile(0.99)

# Crear la columna 'is_outlier' (1 si es outlier, 0 si no lo es)
df['is_outlier'] = ((df['price'] < lower_bound) | (df['price'] > upper_bound)).astype(int)

# Filtrar el DataFrame para mostrar solo los outliers
outliers_df = df[df['is_outlier'] == 1]

df.head()

# Winsorización por categoría
def winsorize_by_category(series):
    lower_bound = series.quantile(0.01)
    upper_bound = series.quantile(0.99)
    return series.clip(lower=lower_bound, upper=upper_bound)

df['price_winsorized'] = df.groupby('category_name')['price'].transform(winsorize_by_category)

print("DataFrame con la nueva columna 'price_winsorized' (primeras 5 filas):")
display(df.head(10))

# Calcular el porcentaje de datos outliers identificados del global
total_records = len(df)
outlier_records = df['is_outlier'].sum()
percentage_outliers = (outlier_records / total_records) * 100

print(f"\nTotal de registros: {total_records}")
print(f"Registros identificados como outliers (globalmente): {outlier_records}")
print(f"Porcentaje de datos outliers (globalmente): {percentage_outliers:.2f}%")

print(f"Número de valores nulos en 'price_winsorized': {df['price_winsorized'].isnull().sum()}")

#Outliers: para la variable de reputación se imputa con la categoria de desconocido

df['seller_reputation_filled'] = df['seller_reputation'].fillna('desconocido')

print("DataFrame con la nueva columna 'seller_reputation_filled' (primeras 5 filas):")
display(df.head())

total_records = len(df)
null_seller_reputation = df['seller_reputation'].isnull().sum()
percentage_null_reputation = (null_seller_reputation / total_records) * 100

print(f"Total de registros en la base de datos: {total_records}")
print(f"Número de valores nulos en 'seller_reputation': {null_seller_reputation}")
print(f"Porcentaje de valores nulos en 'seller_reputation' respecto al global: {percentage_null_reputation:.2f}%")

# Imputar los valores nulos en 'price_winsorized' con la mediana de su 'category_id'
df['price_winsorized'] = df.groupby('category_id')['price_winsorized'].transform(lambda x: x.fillna(x.median()))

print(f"Número de valores nulos en 'price_winsorized' después de la imputación: {df['price_winsorized'].isnull().sum()}")
print("\nDataFrame con la columna 'price_winsorized' imputada (primeras 5 filas):")
display(df.head())

#No se identifica que un seller tenga más de un seller_reputation

# Cantidad de seller_reputation por proveedor, para validar si se puede imputar con otro dato del mismo proveedor y o tro producto
seller_reputation_count = df.groupby('seller_nickname')['seller_reputation'].nunique().reset_index(name='distinct_reputations_count')
display(seller_reputation_count.sort_values(by='distinct_reputations_count', ascending=False))

# Calcular el número total de sellers únicos
total_unique_sellers = df['seller_nickname'].nunique()

# Calcular el número de sellers únicos con una reputación no nula
sellers_with_reputation = df[df['seller_reputation'].notnull()]['seller_nickname'].nunique()

# Calcular el porcentaje de sellers con reputación
percentage_sellers_with_reputation = (sellers_with_reputation / total_unique_sellers) * 100

print(f"Total de sellers únicos en la base de datos: {total_unique_sellers}")
print(f"Número de sellers únicos con 'seller_reputation' no nula: {sellers_with_reputation}")
print(f"Porcentaje de sellers con 'seller_reputation' no nula: {percentage_sellers_with_reputation:.2f}%")

df.head()

df['discount_amount'] = df['regular_price'] - df['price']
display(df[['regular_price', 'price', 'discount_amount']].head())

df.head()

# ==========================================
# 4. CREAR BASE DE DATOS AGRUPADA POR SELLER
# ==========================================

import pandas as pd

# Create dummy variables for categorical columns to get counts per seller
logistic_type_dummies = pd.get_dummies(df['logistic_type'], prefix='logistic')
condition_dummies = pd.get_dummies(df['condition'], prefix='condition')
is_refurbished_dummies = pd.get_dummies(df['is_refurbished'], prefix='refurbished')

# Prepare the DataFrame for aggregation by selecting relevant columns and concatenating dummies
df_for_aggregation = df[[
    'seller_nickname',
    'seller_reputation_filled',
    'titulo',
    'stock',
    'price_winsorized',
    'category_name',
    'discount_amount'
]].copy() # Use .copy() to avoid SettingWithCopyWarning

df_for_aggregation = pd.concat([df_for_aggregation, logistic_type_dummies, condition_dummies, is_refurbished_dummies], axis=1)

# Calculate has_discount_flag: 1 if discount_amount is not null and positive, 0 otherwise
df_for_aggregation['has_discount_flag'] = ((df_for_aggregation['discount_amount'].notna()) & (df_for_aggregation['discount_amount'] > 0)).astype(int)

# Define the aggregation dictionary
agg_dict = {
    'seller_reputation_filled': 'first', # 1. Seller reputation (taking the first non-null value)
    'titulo': 'nunique', # 2. Cantidad de productos distintos (título distinto)
    'stock': ['sum', 'mean'], # 3. Suma de stock, 4. Stock promedio
    'price_winsorized': ['mean', 'median', 'std'], # 7. Promedio precio, 8. Mediana precio, 9. Desviación precio
    'category_name': 'nunique', # 10. Número de categorías distintas
    'has_discount_flag': 'sum', # Corrected: 11. Cantidad de productos que tienen descuento
    'discount_amount': 'mean' # Corrected: 12. Promedio de descuento
}

# Add sum aggregations for dummy variables (logistic_type, condition, is_refurbished)
# These will count the occurrences of each type/condition/refurbished status per seller
for col in logistic_type_dummies.columns:
    agg_dict[col] = 'sum' # Corrected

for col in condition_dummies.columns:
    agg_dict[col] = 'sum' # Corrected

for col in is_refurbished_dummies.columns:
    agg_dict[col] = 'sum' # Corrected

# Group by seller_nickname and apply aggregation
df_seller = df_for_aggregation.groupby('seller_nickname').agg(agg_dict)

# Flatten multi-level column names resulting from multiple aggregations on the same column
df_seller.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_seller.columns.values]

# Rename columns for clarity and to match user's requested names
df_seller = df_seller.rename(columns={
    'seller_reputation_filled_first': 'seller_reputation',
    'titulo_nunique': 'num_distinct_products',
    'stock_sum': 'total_stock',
    'stock_mean': 'avg_stock',
    'price_winsorized_mean': 'avg_price',
    'price_winsorized_median': 'median_price',
    'price_winsorized_std': 'price_std',
    'category_name_nunique': 'num_distinct_categories',
    'has_discount_flag_sum': 'num_products_with_discount',
    'discount_amount_mean': 'avg_discount_amount'
})

df_seller = df_seller.reset_index()

# Display the first few rows of the new DataFrame
print("DataFrame 'df_seller' creado:")
display(df_seller.head())

# Also display info to check columns and types
print("\nInformación del DataFrame 'df_seller':")
df_seller.info()

import pandas as pd

# Create dummy variables for categorical columns to get counts per seller
logistic_type_dummies = pd.get_dummies(df['logistic_type'], prefix='logistic')
condition_dummies = pd.get_dummies(df['condition'], prefix='condition')
is_refurbished_dummies = pd.get_dummies(df['is_refurbished'], prefix='refurbished')

# Prepare the DataFrame for aggregation by selecting relevant columns and concatenating dummies
df_for_aggregation = df[[
    'seller_nickname',
    'seller_reputation_filled',
    'titulo',
    'stock',
    'price_winsorized',
    'category_name',
    'discount_amount'
]].copy() # Use .copy() to avoid SettingWithCopyWarning

df_for_aggregation = pd.concat([df_for_aggregation, logistic_type_dummies, condition_dummies, is_refurbished_dummies], axis=1)

# Calculate has_discount_flag: 1 if discount_amount is not null and positive, 0 otherwise
df_for_aggregation['has_discount_flag'] = ((df_for_aggregation['discount_amount'].notna()) & (df_for_aggregation['discount_amount'] > 0)).astype(int)

# Define the aggregation dictionary
agg_dict = {
    'seller_reputation_filled': 'first', # 1. Seller reputation (taking the first non-null value)
    'titulo': 'nunique', # 2. Cantidad de productos distintos (título distinto)
    'stock': ['sum', 'mean'], # 3. Suma de stock, 4. Stock promedio
    'price_winsorized': ['mean', 'median', 'std'], # 7. Promedio precio, 8. Mediana precio, 9. Desviación precio
    'category_name': 'nunique', # 10. Número de categorías distintas
    'has_discount_flag': 'sum', # Corrected: 11. Cantidad de productos que tienen descuento
    'discount_amount': 'mean' # Corrected: 12. Promedio de descuento
}

# Add sum aggregations for dummy variables (logistic_type, condition, is_refurbished)
# These will count the occurrences of each type/condition/refurbished status per seller
for col in logistic_type_dummies.columns:
    agg_dict[col] = 'sum' # Corrected

for col in condition_dummies.columns:
    agg_dict[col] = 'sum' # Corrected

for col in is_refurbished_dummies.columns:
    agg_dict[col] = 'sum' # Corrected

# Group by seller_nickname and apply aggregation
df_seller = df_for_aggregation.groupby('seller_nickname').agg(agg_dict)

# Flatten multi-level column names resulting from multiple aggregations on the same column
df_seller.columns = ['_'.join(col).strip() if isinstance(col, tuple) else col for col in df_seller.columns.values]

# Rename columns for clarity and to match user's requested names
df_seller = df_seller.rename(columns={
    'seller_reputation_filled_first': 'seller_reputation',
    'titulo_nunique': 'num_distinct_products',
    'stock_sum': 'total_stock',
    'stock_mean': 'avg_stock',
    'price_winsorized_mean': 'avg_price',
    'price_winsorized_median': 'median_price',
    'price_winsorized_std': 'price_std',
    'category_name_nunique': 'num_distinct_categories',
    'has_discount_flag_sum': 'num_products_with_discount',
    'discount_amount_mean': 'avg_discount_amount'
})

df_seller = df_seller.reset_index()

# Display the first few rows of the new DataFrame
print("DataFrame 'df_seller' creado:")
display(df_seller.head())

# Also display info to check columns and types
print("\nInformación del DataFrame 'df_seller':")
df_seller.info()

df_seller.head(20)

# ==========================================
# 2. ANÁLISIS EXPLORATORIO
# ==========================================
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

num_unique_sellers = df['seller_nickname'].nunique()
num_unique_products = df['titulo'].nunique()
num_unique_categories = df['category_name'].nunique()
total_stock_all_products = df['stock'].sum()

print(f"Cantidad de sellers únicos: {num_unique_sellers}")
print(f"Cantidad de productos únicos: {num_unique_products}")
print(f"Cantidad de categorías únicas: {num_unique_categories}")
print(f"Suma total de stock de todos los productos: {total_stock_all_products}")

#La gran mayoría de sellers son sellers pequeños
#muchos sellers con 1 producto // marketplace long tail

# Define custom bins for num_distinct_products to better visualize skewed data
# Most sellers have few products, so initial bins are more granular
bins = [
    0, 1, 2, 3, 4, 5, 10, 20, 50, 100, 200,
    df_seller['num_distinct_products'].max() + 1 # Ensure the last bin captures the max value
]
labels = [
    '1', '2', '3', '4', '5', '6-10', '11-20',
    '21-50', '51-100', '101-200', '200+'
]

# Adjust labels if the number of bins and labels don't match exactly
# This handles cases where max_products might fall outside initially defined labels
if len(bins) - 1 > len(labels):
    # If there are more bins than labels, we might need to adjust the last label
    # or re-evaluate bin strategy. For simplicity here, we truncate labels if needed.
    labels = labels[:len(bins)-1]

# Create a binned column for num_distinct_products
df_seller['num_products_binned'] = pd.cut(
    df_seller['num_distinct_products'],
    bins=bins,
    labels=labels,
    right=False, # Interval is [a, b)
    include_lowest=True
)

# Count sellers in each bin and reindex to maintain order, fill NaN with 0
product_distribution = df_seller['num_products_binned'].value_counts().reindex(labels).fillna(0).astype(int)

# Convert to DataFrame for heatmap, transposing for a column-wise heatmap
product_distribution_df = product_distribution.to_frame(name='Number of Sellers')

# Calculate percentages for annotation
total_sellers_heatmap = product_distribution_df['Number of Sellers'].sum()
annotations = product_distribution_df.apply(lambda x: f"{x['Number of Sellers']}\n({x['Number of Sellers']/total_sellers_heatmap:.1%})", axis=1).values.reshape(-1, 1)

# Create the heatmap
plt.figure(figsize=(8, 10)) # Adjust figure size for better readability
sns.heatmap(product_distribution_df, annot=annotations, fmt='', cmap='YlGnBu', linewidths=.5, linecolor='black')
plt.title('Distribution of Number of Distinct Products per Seller (Heatmap)')
plt.ylabel('Number of Distinct Products (Binned)')
plt.yticks(rotation=0) # Keep y-axis labels horizontal
plt.xlabel('') # No x-label needed for a single column heatmap
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Define custom bins for total_stock to better visualize skewed data
# Stock values can be very high, so create appropriate bins
bins_stock = [
    0, 1, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000,
    df_seller['total_stock'].max() + 1 # Ensure the last bin captures the max value
]
labels_stock = [
    '1', '2-5', '6-10', '11-20', '21-50', '51-100', '101-200',
    '201-500', '501-1000', '1001-2000', '2001-5000', '5000+'
]

# Adjust labels if the number of bins and labels don't match exactly
if len(bins_stock) - 1 > len(labels_stock):
    labels_stock = labels_stock[:len(bins_stock)-1]

# Create a binned column for total_stock
df_seller['total_stock_binned'] = pd.cut(
    df_seller['total_stock'],
    bins=bins_stock,
    labels=labels_stock,
    right=False, # Interval is [a, b)
    include_lowest=True
)

# Count sellers in each bin and reindex to maintain order, fill NaN with 0
stock_distribution = df_seller['total_stock_binned'].value_counts().reindex(labels_stock).fillna(0).astype(int)

# Convert to DataFrame for heatmap, transposing for a column-wise heatmap
stock_distribution_df = stock_distribution.to_frame(name='Number of Sellers')

# Calculate percentages for annotation
total_sellers_heatmap = stock_distribution_df['Number of Sellers'].sum()
annotations = stock_distribution_df.apply(lambda x: f"{x['Number of Sellers']}\n({x['Number of Sellers']/total_sellers_heatmap:.1%})", axis=1).values.reshape(-1, 1)

# Create the heatmap
plt.figure(figsize=(8, 12)) # Adjust figure size for better readability
sns.heatmap(stock_distribution_df, annot=annotations, fmt='', cmap='YlGnBu', linewidths=.5, linecolor='black')
plt.title('Distribution of Total Stock per Seller (Heatmap)')
plt.ylabel('Total Stock (Binned)')
plt.yticks(rotation=0) # Keep y-axis labels horizontal
plt.xlabel('') # No x-label needed for a single column heatmap
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np # Import numpy

# Re-calculate stock_distribution if df_seller has been modified or re-run
# Define custom bins for total_stock to better visualize skewed data
bins_stock = [
    0, 1, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000,
    df_seller['total_stock'].max() + 1 # Ensure the last bin captures the max value
]
labels_stock = [
    '1', '2-5', '6-10', '11-20', '21-50', '51-100', '101-200',
    '201-500', '501-1000', '1001-2000', '2001-5000', '5000+'
]

# Adjust labels if the number of bins and labels don't match exactly
if len(bins_stock) - 1 > len(labels_stock):
    labels_stock = labels_stock[:len(bins_stock)-1]

# Create a binned column for total_stock
df_seller['total_stock_binned'] = pd.cut(
    df_seller['total_stock'],
    bins=bins_stock,
    labels=labels_stock,
    right=False, # Interval is [a, b)
    include_lowest=True
)

# Count sellers in each bin and reindex to maintain order, fill NaN with 0
stock_distribution = df_seller['total_stock_binned'].value_counts().reindex(labels_stock).fillna(0).astype(int)

# Convert to DataFrame for plotting
stock_distribution_df = stock_distribution.to_frame(name='Number of Sellers')
stock_distribution_df['Stock Bins'] = stock_distribution_df.index

plt.figure(figsize=(12, 7))

# Number of colors needed for the palette (equal to the number of stock bins)
n_colors = len(stock_distribution_df['Stock Bins'])

# Get the 'Blues' colormap and create a custom palette from its darker end
# Start from 0.3 (30%) of the colormap to 1.0 (100%) to exclude very light colors
cmap = plt.cm.get_cmap('Blues')
colors = [cmap(i) for i in np.linspace(0.3, 1, n_colors)]
custom_palette = sns.color_palette(colors)

ax = sns.barplot(x='Stock Bins', y='Number of Sellers', data=stock_distribution_df, palette=custom_palette, hue='Number of Sellers', dodge=False, legend=False)
plt.title('Distribución de Sellers por Cantidad Total de Stock')
plt.xlabel('Rango de Stock')
plt.ylabel('Número de Sellers')
plt.xticks(rotation=45, ha='right')

# Remove plot frame
sns.despine(left=True, bottom=True)

# Add annotations (number of sellers and percentage) above each bar
total_sellers = stock_distribution_df['Number of Sellers'].sum()
for container in ax.containers:
    labels = [f'{int(bar.get_height())}\n({bar.get_height()/total_sellers:.1%})' for bar in container]
    ax.bar_label(container, labels=labels, label_type='edge', padding=3)

plt.tight_layout()
plt.show()

# Clean up the temporary binned column if no longer needed
df_seller = df_seller.drop(columns=['total_stock_binned'])

import pandas as pd

# Ensure stock_distribution_df is available (re-creating if needed, as it was dropped in the plotting cell)
# Define custom bins for total_stock to better visualize skewed data
bins_stock = [
    0, 1, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000,
    df_seller['total_stock'].max() + 1 # Ensure the last bin captures the max value
]
labels_stock = [
    '1', '2-5', '6-10', '11-20', '21-50', '51-100', '101-200',
    '201-500', '501-1000', '1001-2000', '2001-5000', '5000+'
]

# Adjust labels if the number of bins and labels don't match exactly
if len(bins_stock) - 1 > len(labels_stock):
    labels_stock = labels_stock[:len(bins_stock)-1]

# Create a binned column for total_stock
df_seller['total_stock_binned'] = pd.cut(
    df_seller['total_stock'],
    bins=bins_stock,
    labels=labels_stock,
    right=False, # Interval is [a, b)
    include_lowest=True
)

# Count sellers in each bin and reindex to maintain order, fill NaN with 0
stock_distribution = df_seller['total_stock_binned'].value_counts().reindex(labels_stock).fillna(0).astype(int)

# Convert to DataFrame for plotting
stock_distribution_df = stock_distribution.to_frame(name='Number of Sellers')
stock_distribution_df['Stock Bins'] = stock_distribution_df.index

# Calculate percentages
total_sellers = stock_distribution_df['Number of Sellers'].sum()
stock_distribution_df['Percentage'] = (stock_distribution_df['Number of Sellers'] / total_sellers) * 100

# Calculate cumulative percentage
stock_distribution_df['Cumulative Percentage'] = stock_distribution_df['Percentage'].cumsum()

# Display the table
display(stock_distribution_df.round(2))

# Clean up the temporary binned column if no longer needed
df_seller = df_seller.drop(columns=['total_stock_binned'])

import pandas as pd

# Ensure total_stock_binned is created for df_seller
bins_stock = [
    0, 1, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000,
    df_seller['total_stock'].max() + 1 # Ensure the last bin captures the max value
]
labels_stock = [
    '1', '2-5', '6-10', '11-20', '21-50', '51-100', '101-200',
    '201-500', '501-1000', '1001-2000', '2001-5000', '5000+'
]

# Adjust labels if the number of bins and labels don't match exactly
if len(bins_stock) - 1 > len(labels_stock):
    labels_stock = labels_stock[:len(bins_stock)-1]

df_seller['total_stock_binned'] = pd.cut(
    df_seller['total_stock'],
    bins=bins_stock,
    labels=labels_stock,
    right=False,
    include_lowest=True
)

# Identify logistic type columns
logistic_cols = ['logistic_DS_sum', 'logistic_FBM_sum', 'logistic_FLEX_sum', 'logistic_Otro_sum', 'logistic_XD_sum']

# Create a temporary DataFrame to process logistic types for each seller
temp_df = df_seller[['seller_nickname', 'total_stock_binned'] + logistic_cols].copy()

# Melt the logistic columns to long format
melted_logistic_df = temp_df.melt(id_vars=['seller_nickname', 'total_stock_binned'],
                                  value_vars=logistic_cols,
                                  var_name='logistic_type_col',
                                  value_name='num_products_with_type')

# Filter to include only rows where the seller uses this logistic type (i.e., has products with it)
melted_logistic_df = melted_logistic_df[melted_logistic_df['num_products_with_type'] > 0]

# Extract clean logistic type name
melted_logistic_df['logistic_type'] = melted_logistic_df['logistic_type_col'].str.replace('_sum', '').str.replace('logistic_', '')

# Group by stock bin and logistic type, then count unique sellers
seller_counts_by_stock_and_logistic = melted_logistic_df.groupby(['total_stock_binned', 'logistic_type'])['seller_nickname'].nunique().unstack(fill_value=0)

# Reindex columns to desired order if necessary and sort index for clarity
desired_logistic_order = ['DS', 'FBM', 'FLEX', 'Otro', 'XD']
seller_counts_by_stock_and_logistic = seller_counts_by_stock_and_logistic.reindex(columns=desired_logistic_order, fill_value=0)

# Display the resulting table
print("Cantidad de Sellers por Rango de Stock y Tipo de Logística:")
display(seller_counts_by_stock_and_logistic)

# Clean up the temporary binned column from df_seller
df_seller = df_seller.drop(columns=['total_stock_binned'])

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Ensure seller_counts_by_stock_and_logistic is available
# If it was dropped or not calculated, re-run the previous cell or ensure data integrity.
# Assuming seller_counts_by_stock_and_logistic is the table generated previously

# Calculate percentages for annotations relative to the total number of sellers
total_sellers_overall = df_seller['seller_nickname'].nunique()
annotations_heatmap = seller_counts_by_stock_and_logistic.applymap(lambda x: f'{x}\n({x/total_sellers_overall:.1%})')

plt.figure(figsize=(14, 8))
sns.heatmap(
    seller_counts_by_stock_and_logistic,
    annot=annotations_heatmap,
    fmt='s', # 's' for string format to display strings
    cmap='Blues', # Using a blue color scheme where darker means more sellers
    linewidths=.5,
    linecolor='white', # White lines for a cleaner separation
    cbar_kws={'label': 'Número de Sellers'}
)

plt.title('Distribución de Sellers por Rango de Stock y Tipo de Logística')
plt.xlabel('Tipo de Logística')
plt.ylabel('Rango de Stock')
plt.yticks(rotation=0) # Keep y-axis labels horizontal
plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()



#La distribución de productos por seller sigue una power law, lo cual es típico en marketplaces.
#Esto significa que un pequeño porcentaje de sellers concentra gran parte del catálogo, mientras que la mayoría tiene una oferta muy pequeña.

#Head sellers → generan volumen
#Long tail → genera diversidad

import matplotlib.pyplot as plt

df_seller['num_distinct_products'].hist(log=True)
plt.title('Distribution of Distinct Products per Seller (Log Scale)')
plt.xlabel('Number of Distinct Products')
plt.ylabel('Number of Sellers (Log Scale)')
plt.show()



# Calculate the count of sellers per reputation
reputation_counts = df_seller['seller_reputation'].value_counts().reset_index()
reputation_counts.columns = ['seller_reputation', 'seller_count']

# Calculate the percentage of sellers per reputation
total_sellers = reputation_counts['seller_count'].sum()
reputation_counts['percentage'] = (reputation_counts['seller_count'] / total_sellers) * 100

print("Cantidad y porcentaje de sellers por seller_reputation:")
display(reputation_counts.round(2))

#Analizar  la cantidad de sellers por su reputación
#La mayoría de sellers tiene reputación positiva,
#pero existe un grupo relevante con reputación media o baja que podría representar riesgo para la experiencia del usuario.

import matplotlib.pyplot as plt
import seaborn as sns

# Define the custom order for seller reputation
custom_reputation_order = [
    'newbie',
    'red',
    'orange',
    'yellow',
    'light_green',
    'green',
    'green_silver',
    'green_gold',
    'green_platinum', # Adding 'green_platinum' as it exists in the data
    'desconocido'    # Adding 'desconocido' for completeness
]

# Ensure 'reputation_counts' is available and re-calculate if necessary
# (Assuming reputation_counts was calculated in a previous cell like e55b018f)
if 'reputation_counts' not in locals():
    reputation_counts = df_seller['seller_reputation'].value_counts().reset_index()
    reputation_counts.columns = ['seller_reputation', 'seller_count']
    total_sellers = reputation_counts['seller_count'].sum()
    reputation_counts['percentage'] = (reputation_counts['seller_count'] / total_sellers) * 100

# Filter and reindex the DataFrame based on the custom order
reputation_counts_ordered = reputation_counts.set_index('seller_reputation').reindex(custom_reputation_order).fillna(0).reset_index()

# Create a DataFrame suitable for heatmap (just the percentage or count column)
# We'll use the percentage for color intensity and custom annotations
heatmap_data = reputation_counts_ordered[['seller_reputation', 'percentage']].set_index('seller_reputation')

# Prepare annotations: combine count and percentage
annotations = reputation_counts_ordered.apply(lambda x: f"{int(x['seller_count'])}\n({x['percentage']:.1f}%) ", axis=1).values.reshape(-1, 1)

# Create the heatmap
plt.figure(figsize=(8, 6)) # Adjust figure size as needed
sns.heatmap(heatmap_data, annot=annotations, fmt='', cmap='YlGnBu', linewidths=.5, linecolor='black')
plt.title('Distribution of Sellers by Reputation (Percentage)')
plt.ylabel('Seller Reputation')
plt.xlabel('') # No x-label needed for a single column heatmap
plt.yticks(rotation=0) # Keep y-axis labels horizontal
plt.tight_layout()
plt.show()

#¿Los sellers grandes tienen mejor reputación?
#sellers con reputación green venden más
#sellers con reputación red tienen pocos productos

custom_reputation_order = [
    'desconocido',
    'newbie',
    'red',
    'orange',
    'yellow',
    'light_green',
    'green',
    'green_silver',
    'green_gold',
    'green_platinum'
]

median_products_by_reputation = df_seller.groupby('seller_reputation')['num_distinct_products'].median()
median_products_by_reputation_ordered = median_products_by_reputation.reindex(custom_reputation_order)

display(median_products_by_reputation_ordered)

custom_reputation_order = [
    'desconocido',
    'newbie',
    'red',
    'orange',
    'yellow',
    'light_green',
    'green',
    'green_silver',
    'green_gold',
    'green_platinum'
]

avg_price_by_reputation = df_seller.groupby('seller_reputation')['avg_price'].mean()
avg_price_by_reputation_ordered = avg_price_by_reputation.reindex(custom_reputation_order)

display(avg_price_by_reputation_ordered)

#¿Los sellers con mejor reputación concentran más catálogo?

df_seller.groupby('seller_reputation')['num_distinct_products'].sum()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Overall Conclusion: There is a strong positive relationship between a seller's reputation and the total stock they manage.
# Higher reputation generally corresponds to a greater quantity of stock, suggesting that consistent inventory management, a broader product offering,
# or the ability to handle larger volumes are characteristics of successful and well-regarded sellers on the platform.


# Define the custom order for seller reputation, including 'desconocido' if present
custom_reputation_order = [
    'desconocido',
    'newbie',
    'red',
    'orange',
    'yellow',
    'light_green',
    'green',
    'green_silver',
    'green_gold',
    'green_platinum'
]

# 1. Define Bins for total_stock (up to 10 bins)
# Using qcut to create approximately equally sized bins based on quantiles
# Adding `duplicates='drop'` to handle cases where there are many identical values at quantiles
# If qcut fails to produce 10 unique bins, it will produce fewer.
df_seller['total_stock_binned'] = pd.qcut(
    df_seller['total_stock'],
    q=min(10, df_seller['total_stock'].nunique()), # Ensure q does not exceed unique values
    labels=False, # Use integer labels for bins initially
    duplicates='drop'
)

# Generate descriptive labels for the bins based on their ranges
bins_with_ranges = pd.qcut(
    df_seller['total_stock'],
    q=min(10, df_seller['total_stock'].nunique()), # Ensure q does not exceed unique values
    duplicates='drop'
)
bin_labels = [str(interval) for interval in bins_with_ranges.cat.categories]
df_seller['total_stock_binned'] = df_seller['total_stock_binned'].map(dict(enumerate(bin_labels)))

# 2. Group and Count sellers by reputation and binned stock
grouped_data = df_seller.groupby(['seller_reputation', 'total_stock_binned']).size().unstack(fill_value=0)

# Reindex rows (seller_reputation) using the custom order, filling missing reputations with 0
grouped_data = grouped_data.reindex(custom_reputation_order, fill_value=0)

# Filter columns to only include bins that were actually created
actual_bin_labels = [label for label in bin_labels if label in grouped_data.columns]
grouped_data = grouped_data[actual_bin_labels]

# Calculate percentages (within each reputation category)
# This calculates the percentage of sellers in each stock bin FOR THAT REPUTATION
percentages = grouped_data.apply(lambda x: x / x.sum() * 100, axis=1).fillna(0)

# Prepare annotations: count and percentage
annotations = grouped_data.astype(str) + '\n(' + percentages.round(1).astype(str) + '%)'

# Create the heatmap
plt.figure(figsize=(14, 8)) # Adjust figure size as needed for readability
sns.heatmap(grouped_data, annot=annotations, fmt='s', cmap='YlGnBu', linewidths=.5, linecolor='black')
plt.title('Distribution of Total Stock by Seller Reputation')
plt.ylabel('Seller Reputation')
plt.xlabel('Total Stock (Binned)')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Clean up the temporary binned column if needed (optional)
df_seller = df_seller.drop(columns=['total_stock_binned'])

import matplotlib.pyplot as plt
import seaborn as sns

# Define the custom order for seller reputation
custom_reputation_order = [
    'newbie',
    'red',
    'orange',
    'yellow',
    'light_green',

    'green',
    'green_silver',
    'green_gold',
    'green_platinum', # Including 'green_platinum' if present
    'desconocido'    # Including 'desconocido' if present
]

# Calculate the sum of distinct products per seller reputation
products_by_reputation_sum = df_seller.groupby('seller_reputation')['num_distinct_products'].sum().reset_index()

# Reindex the DataFrame based on the custom order
products_by_reputation_ordered = products_by_reputation_sum.set_index('seller_reputation').reindex(custom_reputation_order).fillna(0).reset_index()

# Calculate percentages for annotation
total_products_sum = products_by_reputation_ordered['num_distinct_products'].sum()
annotations = products_by_reputation_ordered.apply(lambda x: f"{int(x['num_distinct_products'])}\n({x['num_distinct_products']/total_products_sum:.1%})", axis=1).values.reshape(-1, 1)

# Create the heatmap
plt.figure(figsize=(8, 6)) # Adjust figure size as needed for a smaller plot
sns.heatmap(products_by_reputation_ordered.set_index('seller_reputation'),
            annot=annotations, fmt='', cmap='YlGnBu', linewidths=.5, linecolor='black')
plt.title('Sum of Distinct Products by Seller Reputation')
plt.ylabel('Seller Reputation')
plt.xlabel('Total Distinct Products')
plt.yticks(rotation=0) # Keep y-axis labels horizontal
plt.tight_layout()
plt.show()

sns.histplot(df_seller['num_distinct_products'], log_scale=True)

logistic_cols = [
    'logistic_DS_sum',
    'logistic_FBM_sum',
    'logistic_FLEX_sum',
    'logistic_Otro_sum',
    'logistic_XD_sum'
]

# Calculate the number of distinct logistic types used by each seller
df_seller['num_logistic_types'] = df_seller[logistic_cols].apply(lambda x: (x > 0).sum(), axis=1)

# Filter sellers that use more than one logistic type
sellers_with_multiple_logistics = df_seller[df_seller['num_logistic_types'] > 1]

print(f"Número de sellers que usan más de un tipo de logística: {len(sellers_with_multiple_logistics)}")
display(sellers_with_multiple_logistics[['seller_nickname', 'num_distinct_products', 'num_logistic_types'] + logistic_cols].head())

#TIPOS DE SELLER
#muchos productos + pocas categorías	especialista
#muchos productos + muchas categorías	retailer
#pocos productos	seller ocasional


sns.scatterplot(
    data=df_seller,
    x="num_distinct_products",
    y="num_distinct_categories"
)

sns.scatterplot(
    data=df_seller,
    x="avg_price",
    y="price_std"
)

df_seller['discount_ratio'] = df_seller['num_products_with_discount'] / df_seller['num_distinct_products']
sns.histplot(df_seller['discount_ratio'])

df_seller['fulfillment_ratio'] = df_seller['logistic_FBM_sum'] / df_seller['num_distinct_products']
sns.scatterplot(
    data=df_seller,
    x="num_distinct_products",
    y="fulfillment_ratio"
)

df_seller.groupby('seller_reputation')['num_distinct_products'].median()

from sklearn.preprocessing import StandardScaler

#Define la lista de variables

# Define the list of features for clustering (excluding seller_nickname and seller_reputation, which are categorical/identifiers)
features = [
    'num_distinct_products',
    'total_stock',
    'median_price',
    'avg_discount_amount',
    #'num_logistic_types',

]

# Handle potential NaN values in the selected features before scaling
# For simplicity, filling with 0 or the mean/median is common. Here, we'll fill with 0.
# This is important for 'price_std' and 'avg_discount_amount' which can have NaNs if a seller has only one product or no discounts.
df_seller[features] = df_seller[features].fillna(0)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_seller[features])

df_seller.info()

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []

for k in range(2, 10):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init='auto')
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(range(2, 10), inertia, marker='o', linestyle='--')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal k')
plt.xticks(range(2, 10))
plt.grid(True)
plt.show()

print("Observe the plot above. The 'elbow' point, where the decrease in inertia starts to slow down significantly, is usually considered the optimal number of clusters.")

from sklearn.cluster import KMeans

inertia = []

for k in range(5,10):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

kmeans = KMeans(n_clusters= 4, random_state=42)
df_seller['cluster'] = kmeans.fit_predict(X_scaled)

#EVALUACION DE LOS CLUSTER
#Coeficiente de Silueta (Silhouette Score):
from sklearn.metrics import silhouette_score

# Calculate the Silhouette Coefficient
silhouette_avg = silhouette_score(X_scaled, df_seller['cluster'])

print(f"El Coeficiente de Silueta para los clusters es: {silhouette_avg:.3f}")

cluster_summary = df_seller.groupby('cluster')[features].mean()
cluster_counts = df_seller['cluster'].value_counts().sort_index()

cluster_summary['num_sellers'] = cluster_counts

print("Estadísticas promedio de los clusters y cantidad de sellers:")
display(cluster_summary)

"""##**Parte 2 - Gen AI**"""

import os
from google.colab import userdata

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

df_seller.head()

def build_prompt(seller_data, seller_nickname, cluster_id, cluster_description):

    prompt = f"""
You are a senior commercial strategy analyst at Mercado Libre.

Your task is to help the commercial team design strategies to manage marketplace sellers.

The goal is NOT to advise the seller directly. The goal is to recommend actions that Mercado Libre's commercial team should take to:
- retain high-value sellers
- increase seller performance
- help sellers move into stronger clusters
- prioritize commercial resources efficiently

You will receive information about a seller and the cluster they belong to.

{cluster_description}

--------------------------------------------------
SELLER INFORMATION
--------------------------------------------------

Seller nickname: {seller_nickname}

Cluster: {cluster_id}

Cluster description:
{cluster_description}

Seller metrics:
{seller_data}

--------------------------------------------------
TASK
--------------------------------------------------

1. Analyze the seller profile relative to the cluster characteristics.
2. Briefly explain why this seller fits into this cluster.
3. Identify the main commercial opportunity for Mercado Libre.
4. Propose strategic actions for Mercado Libre's commercial team.

The strategies must aim to:
- increase seller sales
- improve marketplace engagement
- retain high-performing sellers
- help sellers move into stronger clusters when possible

--------------------------------------------------
OUTPUT FORMAT (in Spanish)
--------------------------------------------------

Respond in a concise executive format.
Each section must contain a maximum of 2 lines.
Use bullet points instead of long paragraphs.

Seller: <nickname>
Cluster: <cluster_name>

Diagnóstico
- bullet
- bullet

Oportunidad
- bullet

Acciones recomendadas (equipo comercial)
1.
2.
3.
4.
5.

Prioridad: Alta / Media / Baja

Impacto esperado
- bullet
"""

    return prompt

from openai import OpenAI
client = OpenAI()

def generar_estrategia(seller_nickname):

    seller_row = df_seller[df_seller["seller_nickname"] == seller_nickname]

    if seller_row.empty:
        return "Seller no encontrado"

    row = seller_row.iloc[0]

    # Prepare seller_data in a readable format for the prompt
    seller_data = {
        "num_distinct_products": row["num_distinct_products"],
        "total_stock": row["total_stock"],
        "median_price": round(row["median_price"], 2),
        "avg_discount_amount": round(row["avg_discount_amount"], 2),
        "seller_reputation": row["seller_reputation"],
        "num_distinct_categories": row["num_distinct_categories"],
        "num_products_with_discount": row["num_products_with_discount"]
    }

    # Get the cluster description based on the cluster ID
    cluster_id = row['cluster']
    cluster_descriptions = [
        "Small sellers with very limited catalogs and moderate inventory. They represent the majority of the marketplace but usually have low commercial activity. Main opportunity: activation and gradual growth.",
        "Sellers who apply extremely aggressive discounts. They may be clearing inventory or competing heavily on price. Main opportunity: pricing optimization and margin protection.",
        "Sellers with significant inventory and medium product catalogs. They show strong growth potential and could evolve into strategic sellers. Main opportunity: scale operations and expand catalog.",
        "Sellers with very few products but extremely high prices. Typically niche or specialized products with high value per transaction. Main opportunity: improve visibility and conversion."
    ]
    # Adjusting for 0-indexed list if cluster_id starts from 0
    cluster_desc = cluster_descriptions[int(cluster_id)]

    prompt = build_prompt(
        seller_data=seller_data,
        seller_nickname=seller_nickname,
        cluster_id=int(cluster_id),
        cluster_description=cluster_desc
    )

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role":"system","content":"You are a senior commercial strategy analyst at Mercado Libre."},
            {"role":"user","content":prompt}
        ],
        temperature=0.7
    )

    return response.choices[0].message.content

generar_estrategia("000e60a7db")

df_seller.to_csv("df_seller.csv", index=False)

